/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TtpbjgAYdeB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Hero() {
  return (
    (<Carousel className="w-full h-[80vh] max-h-[600px] bg-gray-100 dark:bg-gray-800">
      <CarouselContent>
        <CarouselItem>
          <div
            className="flex flex-col items-center justify-center h-full px-4 md:px-6 text-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                Unlock the Power of Web Development
              </h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Discover the ultimate toolkit for building stunning web experiences. Streamline your workflow and
                unleash your creativity.
              </p>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#">
              Get Started
            </Link>
          </div>
          <img
            alt="Hero Image"
            className="absolute inset-0 w-full h-full object-cover"
            height="600"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1600/600",
              objectFit: "cover",
            }}
            width="1600" />
        </CarouselItem>
        <CarouselItem>
          <div
            className="flex flex-col items-center justify-center h-full px-4 md:px-6 text-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                Elevate Your Web Presence
              </h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Craft stunning websites that captivate your audience and drive results. Our platform empowers you to
                bring your vision to life.
              </p>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#">
              Explore Features
            </Link>
          </div>
          <img
            alt="Hero Image"
            className="absolute inset-0 w-full h-full object-cover"
            height="600"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1600/600",
              objectFit: "cover",
            }}
            width="1600" />
        </CarouselItem>
        <CarouselItem>
          <div
            className="flex flex-col items-center justify-center h-full px-4 md:px-6 text-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                Unleash Your Creativity
              </h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Harness the power of our intuitive tools and components to bring your ideas to life. Effortlessly craft
                stunning web experiences.
              </p>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#">
              Start Building
            </Link>
          </div>
          <img
            alt="Hero Image"
            className="absolute inset-0 w-full h-full object-cover"
            height="600"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1600/600",
              objectFit: "cover",
            }}
            width="1600" />
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious
        className="absolute left-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-white/50 p-2 text-gray-900 shadow-md transition-colors hover:bg-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-950/50 dark:text-gray-50 dark:hover:bg-gray-800 dark:focus-visible:ring-gray-300">
        <ChevronLeftIcon className="h-6 w-6" />
      </CarouselPrevious>
      <CarouselNext
        className="absolute right-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-white/50 p-2 text-gray-900 shadow-md transition-colors hover:bg-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-950/50 dark:text-gray-50 dark:hover:bg-gray-800 dark:focus-visible:ring-gray-300">
        <ChevronRightIcon className="h-6 w-6" />
      </CarouselNext>
    </Carousel>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
